### ISSUE TITLE
Consider making this repo standalone

### ISSUE THREAD

**Issue by yberreby** [nickel-org/rust-mustache#26]
Neither the [original rust-mustache](https://github.com/SimonPersson/rust-mustache) nor [rustache](https://github.com/rustache/rustache) are being actively maintained, making this project the only 'reasonable' alternative. Consider making it a [standalone repository](https://stackoverflow.com/questions/18390249/github-make-fork-an-own-project) to emphasize this fact.

**Comment by bfrog** [comment]
+1

**Comment by SimonPersson** [comment]
I guess we've been hesitant to do that as we're not the original authors of the project. I agree that the current situation is not optimal though.

@erickt, do you have any intention to work on rust-mustache again? If not, would you mind if we turned it into a standalone repository?

**Comment by erickt** [comment]
@SimonPersson: I've sadly been too busy, so no, I haven't had time to work on it. I'd be happy to transfer maintenance over the crate to this project if you want.

**Comment by SimonPersson** [comment]
@erickt: That'd be great. Thanks!

@Ryman, @cburgdorf: Do you see any reason not to turn this into a standalone repo?

**Comment by Ryman** [comment]
My only thoughts are that it might make sense to bring it under another organisation, or to merge upstream and add maintainers there for better searchability? Other than that I think it'd be good to not be a fork anymore so it's less confusing for users :+1:

**Comment by cburgdorf** [comment]
I think it would make most sense to create a new organization and close down all forks. One thing, that I'm not completely sure about is if @erickt should than transfer ownership of the original repository over to that new organization, so that GitHub will automatically redirect to it.

We could then either force push our version into that repo or use the git merge strategy `ours` to supersede with our version without the need of a force push.

The alternative would be to just close down all forks with a final commit that changes the readme to something like **DO NOT USE THIS, USE THAT INSTEAD**. But this may still leave room for rare occasions that people create issues in the wrong repository because they didn't see the readme as they directly jumped to /issues or so.

**Comment by ninjabear** [comment]
+1

**Comment by erickt** [comment]
I've added a "don't use this repo" and a pointer to this project. I've also given @cburgdorf / @Ryman   collaborator-status on https://github.com/erickt/rust-mustache. The two of you already have permission to the crates.io crate.

I don't think there's a strict need to make a separate organization for mustache, you could just release this repository as the "mustache v0.8.0" crate and carry on from there.

**Comment by SirVer** [comment]
fwiw, when I moved main development for https://github.com/SirVer/ultisnips to Github, another user already had an in-official fork. After asking his d'accord, I emailed github and asked for https://github.com/SirVer/ultisnips to become the root of all projects (so that it becomes the official one everything else is "forked from" in the UI and graphs). Maybe this could be done here too?

**Comment by petehayes102** [comment]
Is there any movement on this? Seems like v0.4 is still the latest on crates.io.

**Comment by petehayes102** [comment]
Just realised that there's two crates - "rust-mustache" and "mustache". Ignore me...

**Comment by ninjabear** [comment]
Gentle bump @Ryman @cburgdorf 

I'm happy to become a maintainer if it means this project is pulled out of the strange condition it's in (spread across many repos)

**Comment by ninjabear** [comment]
hey @Ryman ! Yep of course let me know what you need

**Comment by Ryman** [comment]
@ninjabear I've added you as a collaborator for the repo, if you could chime in on #53 or #55 when you get a chance that would be great!

Closing this issue as it's now resolved via #48 :)
